### ISSUE TITLE
StateMetadataUtils hides actual errors

### ISSUE THREAD

**Issue by juhoautio** [king/bravo#15]
Looks like not catching `Throwable` https://github.com/king/bravo/pull/13 wasn't enough yet.

I got this error:

```
java.lang.IllegalStateException: Cannot read state of a stateless operator.
	at com.king.bravo.reader.OperatorStateReader.lambda$readKeyedStates$6(OperatorStateReader.java:101)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.king.bravo.reader.OperatorStateReader.readKeyedStates(OperatorStateReader.java:101)
```

The actual cause was another `Exception`, which got silently ignored here:

https://github.com/king/bravo/blob/6013d095750cd7f9fbf46ed47510b42ab4df4eaf/bravo/src/main/java/com/king/bravo/utils/StateMetadataUtils.java#L137-L139

Any reason to return `Optional.empty()` here instead of throwing a runtime exception (that wraps the original exception)?

I found the actual exception with debugger:

> java.lang.RuntimeException: org.apache.flink.core.fs.UnsupportedFileSystemSchemeException: Could not find a file system implementation for scheme 's3'. The scheme is not directly supported by Flink and no Hadoop file system to support this scheme could be loaded.

Yeah, apparently that happens because I had copied the savepoint from its original s3 location to my local machine (is it really so that even savepoint folders can't be moved anywhere from their original location?)

**Comment by gyfora** [comment]
I think Flink savepoints have absolute path references inside their metadata so you cant really move them around. :/

But you are probably write we should just throw these exceptions
